// Generated by CoffeeScript 1.7.1
(function() {
  var Rabbit, fatRabbit, layer, rect, stage, whiteRabbit;

  stage = new Kinetic.Stage({
    container: "canvas_container",
    width: 300,
    height: 360
  });

  layer = new Kinetic.Layer();

  rect = new Kinetic.Rect({
    x: 10,
    y: 10,
    width: 20,
    height: 20,
    fill: "green",
    strokeWidth: 4
  });

  console.log(rect.x(50));

  layer.add(rect);

  stage.add(layer);

  Rabbit = (function() {
    function Rabbit(adjective) {
      this.adjective = adjective;
    }

    Rabbit.prototype.speak = function(line) {
      return console.log("The " + this.adjective + " rabbit says '" + line + "'");
    };

    return Rabbit;

  })();

  whiteRabbit = new Rabbit("white");

  fatRabbit = new Rabbit("fat");

  whiteRabbit.speak("Hurry!");

  fatRabbit.speak("Tasty");

}).call(this);
